/* 换成你自己的内容后，保存并刷新即可。
   type 为 post 或 note 时，点击进入 Markdown 页。页面上都叫博客或笔记。
   type 为 paper 时，页面上同样显示为博客，只列出题目、时间、期刊和摘要。
   date 用 YYYY-MM-DD。首页按日期从新到旧排列。
   launched 是站点起始日，用来计算已运行时间。
   updated 留空时，最后更新时间取最新一篇的日期。
*/
window.SITE = {
  name: "LiferAl",
  bio: "Computer Science at Beihang University",
  launched: "2025-09-01",
  updated: "",
  github: "https://github.com/LiferAl",
  email: "lmk060507@buaa.edu.cn",
  announcement: "现在的文章是示例。打开 js/site.js，按同样的格式换成你自己的简介、博客和笔记。",
  tools: [
    { title: "GitHub", url: "https://github.com/LiferAl", desc: "代码仓库" }
  ],
  posts: [
    {
      id: "lab-note-shape",
      type: "post",
      title: "实验报告里固定留下的四段",
      date: "2026-08-12",
      tags: ["实验", "写作"],
      summary: "题目和结论放在最上面，代码只留关键路径，现象和命令分开写，隔一个月还能看懂。",
      body: [
        "实验报告写完当时都觉得清楚，隔一个月再打开，常常只剩下一段贴上去的输出。下面四段是我现在写操作系统实验和课程项目时固定会留的。",
        "",
        "## 结论先写",
        "",
        "第一段用两三句话写这次做完了什么、结果对不对。审报告的人和两个月后的自己都从这里进入。背景放到后面。",
        "",
        "## 只贴关键路径",
        "",
        "整文件粘进报告里几乎不会再被阅读。留下会改行为的那几十行，并在旁边写它依赖的不变量。",
        "",
        "```c",
        "void timer_intr(void) {",
        "    ticks++;",
        "    current->slice--;",
        "    if (current->slice > 0) return;",
        "    current->slice = DEFAULT_SLICE;",
        "    schedule();",
        "}",
        "```",
        "",
        "## 和预期不符的现象",
        "",
        "单独写「我以为会发生什么」和「实际打印了什么」。修完之后这段仍然留着，它比最终正确的代码更能提醒坑在哪里。",
        "",
        "## 下次要敲的命令",
        "",
        "```bash",
        "make clean && make",
        "qemu-system-i386 -nographic -serial mon:stdio -kernel kernel.elf",
        "```",
        "",
        "命令、输入样例、期望输出放在同一节。报告就变成可以重新执行的笔记，而不是一篇回忆。"
      ].join("\n")
    },
    {
      id: "os-timer-sched",
      type: "note",
      title: "时钟中断里的进程调度",
      date: "2026-06-18",
      tags: ["操作系统", "实验"],
      summary: "时间片放在时钟中断里扣，而不是在每个系统调用返回时都检查一遍。",
      body: [
        "时钟中断每 10ms 进来一次。调度不放在系统调用返回的公共路径上，只在中断里累计 tick，时间片用完再挑下一个进程。",
        "",
        "## 时间片",
        "",
        "就绪队列用循环链表。当前进程用完 `slice` 之后摘下来挂到队尾，避免它立刻又被选中。",
        "",
        "```c",
        "void timer_intr(void) {",
        "    ticks++;",
        "    current->slice--;",
        "    if (current->slice > 0) return;",
        "    current->slice = DEFAULT_SLICE;",
        "    schedule();",
        "}",
        "```",
        "",
        "`schedule()` 只交换 `curproc` 和内核栈。中断处理函数里不能睡眠，所以这里不做可能阻塞的锁检查。",
        "",
        "## 踩过的地方",
        "",
        "忘了恢复陷阱帧里的返回地址时，进程会从中断入口再跑一遍，看起来像时间片永远不结束。打印 `ticks` 和当前 `pid` 比单步看切换更快定位。",
        "",
        "> 切换前后各打一行。如果只在切换之后打，被抢占的进程永远没有自己的日志。"
      ].join("\n")
    },
    {
      id: "svm-review",
      type: "note",
      title: "支持向量机复习",
      date: "2026-05-09",
      tags: ["机器学习", "复习"],
      summary: "硬间隔、对偶和核函数：间隔只由支持向量决定，核从对偶问题里换进去。",
      body: [
        "复习时先写原问题，再写哪些样本真正参与了间隔。软间隔和核都是在这个骨架上改约束或改内积。",
        "",
        "## 硬间隔",
        "",
        "两类线性可分时，间隔是两条支持平面之间的距离。把 $\\lVert w \\rVert$ 收进目标里：",
        "",
        "$$\\min_{w,b} \\frac{1}{2}\\lVert w \\rVert^{2}$$",
        "",
        "约束是 $y_i(w^{\\top} x_i+b)\\ge 1$。落在边界上的点是支持向量，其余点的约束是松的，去掉它们最优解不变。",
        "",
        "## 对偶",
        "",
        "拉格朗日函数把约束吸进来：",
        "",
        "$$L(w,b,\\alpha)=\\frac{1}{2}\\lVert w \\rVert^{2}-\\sum_i \\alpha_i\\big[y_i(w^{\\top} x_i+b)-1\\big]$$",
        "",
        "对 $w$ 和 $b$ 求导并代回，决策只依赖内积 $\\langle x_i,x\\rangle$。核函数就是在这一步把内积换成 $K(x_i,x)$，原空间不必真的把 $\\phi(x)$ 写出来。",
        "",
        "## 软间隔要记的一句",
        "",
        "松弛变量允许点跑进间隔甚至跨过平面，惩罚系数 $C$ 越大越接近硬间隔。考试里如果问「$C\\to 0$ 时模型怎样」，答案是间隔优先、错分变便宜，而不是核消失。"
      ].join("\n")
    },
    {
      id: "attention-notes",
      type: "note",
      title: "论文笔记：Attention Is All You Need",
      date: "2026-03-22",
      tags: ["论文", "机器学习"],
      summary: "缩放点积注意力、多头，以及为什么要除掉维度的平方根。",
      body: [
        "这篇笔记只留公式和我当时卡住的地方，不复述整篇文章的结构。",
        "",
        "## 缩放点积",
        "",
        "查询、键、值都是向量序列。注意力是对值的加权平均，权重来自查询和键的相似度：",
        "",
        "$$\\mathrm{Attention}(Q,K,V)=\\mathrm{softmax}\\!\\left(\\frac{QK^{\\top}}{\\sqrt{d_k}}\\right)V$$",
        "",
        "除以 $\\sqrt{d_k}$ 是因为点积的方差随维度涨。维度大时点积绝对值变大，softmax 几乎变成 one-hot，梯度就很瘦。",
        "",
        "```python",
        "import math",
        "",
        "def attention(q, k, v):",
        "    scale = math.sqrt(k.shape[-1])",
        "    weights = softmax(q @ k.T / scale)",
        "    return weights @ v",
        "```",
        "",
        "## 多头在做什么",
        "",
        "把同一组 $Q,K,V$ 线性投影到 $h$ 个较低的子空间，各自做注意力再拼回去。不同的头可以看不同的位置关系，最后一次投影把它们混回模型宽度。",
        "",
        "读代码时先对上三个张量的形状：`[batch, heads, seq, dim]`。形状一对，掩码该加在 softmax 之前就很清楚。"
      ].join("\n")
    },
    {
      id: "algo-final-recall",
      type: "note",
      title: "算法试卷回忆：最短路与摊还",
      date: "2026-01-16",
      tags: ["算法", "考试"],
      summary: "一道非负边最短路，一道动态数组的摊还。记下题面、做法和我写错的那一步。",
      body: [
        "这是一份回忆的写法示例：题面用自己的话压缩，下面写当时的做法和错处。它不是原卷。",
        "",
        "## 非负边最短路",
        "",
        "题面大致是：有向图边权非负，求 $s$ 到其余各点的最短路，并说明不能改用 Bellman-Ford 的原因以外，为什么 Dijkstra 在这里是对的。",
        "",
        "我用二叉堆。松弛成功就把新的距离再压进堆，不支持 decrease-key，所以同一个点可能入堆多次。",
        "",
        "```cpp",
        "using Node = pair<long long, int>;",
        "priority_queue<Node, vector<Node>, greater<Node>> pq;",
        "dist[s] = 0;",
        "pq.push({0, s});",
        "while (!pq.empty()) {",
        "    auto [d, u] = pq.top();",
        "    pq.pop();",
        "    if (d != dist[u]) continue;",
        "    for (auto [v, w] : graph[u]) {",
        "        if (dist[v] > d + w) {",
        "            dist[v] = d + w;",
        "            pq.push({dist[v], v});",
        "        }",
        "    }",
        "}",
        "```",
        "",
        "复杂度写成 $O((n+m)\\log n)$。边权非负时，第一次弹出的距离就是最短路，后面的过期副本被 `d != dist[u]` 丢掉。",
        "",
        "## 动态数组扩容",
        "",
        "连续表满了就申请两倍空间并拷贝。单次插入最坏是 $O(n)$，但 $n$ 次插入的总拷贝次数小于 $2n$。",
        "",
        "| 操作 | 当时的答案 | 容易漏掉的一句 |",
        "| --- | --- | --- |",
        "| 单次插入 | 最坏 $O(n)$ | 摊还是 $O(1)$ |",
        "| n 次插入 | 总拷贝 $< 2n$ | 倍增，不是固定加一块 |",
        "| 出队 | 不释放空间 | 摊还分析里不要顺便收缩 |",
        "",
        "我当时把收缩也算进了同一套势能，势能会变成负的。回忆里把「只扩不缩」单独写出来，下次就不会再混。"
      ].join("\n")
    },
    {
      id: "sample-paper",
      type: "paper",
      title: "示例：把论文题目写在这里",
      date: "2025-11-02",
      journal: "示例期刊，卷 1，页 1–10",
      tags: ["博客"],
      abstract: "这是一条 publication 示例。首页和 paper 页只显示题目、时间、期刊和摘要，不会打开 Markdown 阅读页。把 title、date、journal、abstract 换成你自己的论文；如果有公开链接，加上 url 字段就会出现「原文」。",
      url: ""
    }
  ]
};
